### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Hadhab** [PhazeRoOman/thawani-for-woocommerce#82] opened 2022-04-09 04:09 UTC
Showing server error when using points discount

**Comment by Hadhab** [comment] 2022-04-09 04:09
My website: www.hadhab.com

**Comment by Hadhab** [comment] 2022-04-09 04:11
Also is not generated from wp-admin

**Comment by w7shdev** [comment] 2022-04-09 10:03
Hey @Hadhab 
this is a duplicate of #50  and #51 . 

TL;DR

Thawani Pay API, is not supporting coupon discount by design. So you have to work around this and communicate it with Thawani Pay support.

**Comment by w7shdev** [comment] 2022-04-19 13:02
@Ma7eer can we close this out

**Comment by Hadhab** [comment] 2022-04-19 15:12
Yes, thank you for the support

**Closed** 2022-04-23 10:32 UTC
